"use strict";
exports.__esModule = true;
var FirebaseAnalyticEvent;
(function (FirebaseAnalyticEvent) {
    FirebaseAnalyticEvent["recipeCreated"] = "recipe_created";
    FirebaseAnalyticEvent["ingredientCreated"] = "ingredient_created";
    FirebaseAnalyticEvent["recipeSearch"] = "recipe_search";
    FirebaseAnalyticEvent["recipeRatingSet"] = "recipe_rating_set";
    FirebaseAnalyticEvent["recipeCommentCreated"] = "recipe_comment_created";
    FirebaseAnalyticEvent["recipeShowPreviousComment"] = "recipe_show_previous_comments";
    FirebaseAnalyticEvent["eventCreated"] = "event_created";
    FirebaseAnalyticEvent["eventGetActual"] = "event_get_actual";
    FirebaseAnalyticEvent["eventGetHistory"] = "event_get_history";
    FirebaseAnalyticEvent["eventCookAdded"] = "event_cook_added";
    FirebaseAnalyticEvent["userCreated"] = "user_created";
    FirebaseAnalyticEvent["userChangedEmail"] = "user_changed_email";
    FirebaseAnalyticEvent["userChangedPassword"] = "user_changed_password";
    FirebaseAnalyticEvent["userResetetPassword"] = "user_reseted_password";
    FirebaseAnalyticEvent["unitCreated"] = "unit_created";
    FirebaseAnalyticEvent["unitConversionCreated"] = "unit_conversion_created";
    FirebaseAnalyticEvent["departmentCreated"] = "department_created";
    FirebaseAnalyticEvent["departmentUpdated"] = "department_updated";
    FirebaseAnalyticEvent["shoppingListGenerated"] = "shopping_list_generated";
    FirebaseAnalyticEvent["menuplanCreated"] = "menuplan_created";
    FirebaseAnalyticEvent["menuplanGet"] = "menuplan_get";
    FirebaseAnalyticEvent["quantityCalculationCreated"] = "quantity_calculation_created";
    FirebaseAnalyticEvent["uploadPicture"] = "upload_picture";
    FirebaseAnalyticEvent["deletePicture"] = "delete_picture";
    FirebaseAnalyticEvent["appForceRefresh"] = "app_force_refresh";
    FirebaseAnalyticEvent["cloudFunctionExecuted"] = "cloud_function_executed";
})(FirebaseAnalyticEvent = exports.FirebaseAnalyticEvent || (exports.FirebaseAnalyticEvent = {}));
exports["default"] = FirebaseAnalyticEvent;
